/* ============================================================
   VISORA — templates.js
   AUTO-GENERATED — DO NOT EDIT THIS FILE DIRECTLY

   Source of truth: davetiye websiteleri/[folder]/visora.json
   To regenerate:  node visora-build.js
   To watch:       node visora-watch.js

   Adding a new invitation:
     1. Create a folder inside "davetiye websiteleri/"
     2. Place visora.json inside with metadata + segments
     3. Run: node visora-build.js
   ============================================================ */

window.VISORA_TEMPLATES = [
  {
    "id": "wedding-video",
    "demo": "index.html",
    "nameTR": "Timeless Romance",
    "nameEN": "Timeless Romance",
    "catTR": "Düğün",
    "catEN": "Wedding",
    "descTR": "En değerli anılarınızı romantik bir hikâye akışıyla misafirlerinize sunan zamansız bir tasarım.",
    "descEN": "A timeless design presenting your most cherished memories to your guests in a romantic narrative flow.",
    "preview": "images/hero.png",
    "features": [
      "countdown",
      "music",
      "gallery",
      "video"
    ],
    "badge": null,
    "featured": true,
    "order": 1,
    "cardStyle": {
      "bg": "images/hero.png",
      "kolBg": "img/koleksiyonlar görsel/timeless romance karanlık.png",
      "kolBgLight": "img/koleksiyonlar görsel/timeless romance aydınlık.png",
      "theme": "timeless",
      "invLabel": "DÜĞÜN DAVETİYESİ",
      "name1Field": "bride-name",
      "ampText": "&",
      "name2Field": "groom-name",
      "dateField": "event-date"
    },
    "segments": [
      {
        "id": null,
        "tabLabel": null,
        "labelTR": "Düğün",
        "labelEN": "Wedding",
        "scrollTarget": "hero",
        "tabKey": null,
        "timelineFormat": "wedding-video",
        "timelineItems": [
          { "time": "16:00", "title": "Konvoy",             "icon": "images/car.png" },
          { "time": "19:00", "title": "Nikâh & Karşılama",  "icon": "images/arch.png" },
          { "time": "20:00", "title": "İlk Dans & Kutlama", "icon": "images/couple.png" },
          { "time": "21:00", "title": "Pasta & Takı",       "icon": "images/cake.png" },
          { "time": "22:00", "title": "After Party",        "icon": "images/party.png" },
          { "time": "23:00", "title": "Fotoğraf",           "icon": "images/photo.png" }
        ],
        "sectionGroups": [
          { "id": "couple",   "labelTR": "Çift Bilgileri", "labelEN": "Couple Details",  "scrollTarget": "hero" },
          { "id": "datetime", "labelTR": "Tarih & Saat",   "labelEN": "Date & Time",     "scrollTarget": "hero" },
          { "id": "venue",    "labelTR": "Mekan",          "labelEN": "Venue",           "scrollTarget": "venue" },
          { "id": "message",  "labelTR": "Davet Metni",    "labelEN": "Invitation Text", "scrollTarget": "message" },
          { "id": "family",   "labelTR": "Aile İsimleri",  "labelEN": "Family Names",    "scrollTarget": "family" }
        ],
        "fieldMap": [
          { "id": "hero-image",     "section": "couple",   "type": "image",    "labelTR": "Kapak Fotoğrafı",  "labelEN": "Cover Photo",     "placeholder": "",                     "defaultValue": "" },
          { "id": "bride-name",     "section": "couple",   "type": "text",     "labelTR": "Gelin Adı",        "labelEN": "Bride Name",      "placeholder": "Senem",                "defaultValue": "SENEM" },
          { "id": "groom-name",     "section": "couple",   "type": "text",     "labelTR": "Damat Adı",        "labelEN": "Groom Name",      "placeholder": "Mehmet",               "defaultValue": "MEHMET" },
          { "id": "event-date",     "section": "datetime", "type": "text",     "labelTR": "Tarih",            "labelEN": "Date",            "placeholder": "23 AĞUSTOS 2026",      "defaultValue": "23 Ağustos 2026" },
          { "id": "event-time",     "section": "datetime", "type": "time",     "labelTR": "Saat",             "labelEN": "Time",            "placeholder": "20:00",                "defaultValue": "20:00" },
          { "id": "venue-name",     "section": "venue",    "type": "text",     "labelTR": "Mekan Adı",        "labelEN": "Venue Name",      "placeholder": "Gloria Meram",         "defaultValue": "GLORIA MERAM" },
          { "id": "venue-address",  "section": "venue",    "type": "text",     "labelTR": "Adres",            "labelEN": "Address",         "placeholder": "Konya",                "defaultValue": "Lalebahçe, Özgüven Sk. No:1, 42140 Meram/Konya" },
          { "id": "map-link",       "section": "venue",    "type": "url",      "labelTR": "Harita URL",       "labelEN": "Map URL",         "placeholder": "https://maps.google.com/...", "defaultValue": "" },
          { "id": "invite-message", "section": "message",  "type": "textarea", "labelTR": "Davet Metni",      "labelEN": "Invitation Text", "placeholder": "Bu mutlu günümüzde...", "defaultValue": "Bu mutlu günümüzde sizleri de aramızda görmekten mutluluk duyarız." },
          { "id": "bride-family",   "section": "family",   "type": "text",     "labelTR": "Gelin Ailesi",     "labelEN": "Bride Family",    "placeholder": "YILMAZ AİLESİ",        "defaultValue": "YILMAZ AİLESİ" },
          { "id": "groom-family",   "section": "family",   "type": "text",     "labelTR": "Damat Ailesi",     "labelEN": "Groom Family",    "placeholder": "KARA AİLESİ",          "defaultValue": "KARA AİLESİ" }
        ]
      }
    ],
    "folder": "wedding"
  },
  {
    "id": "slot-machine-save-date",
    "demo": "index.html",
    "nameTR": "Timeless Lucky",
    "nameEN": "Timeless Lucky",
    "catTR": "Düğün",
    "catEN": "Wedding",
    "descTR": "Vintage slot makinesi konseptiyle tasarlanan, tarihi sürpriz bir deneyimle ortaya çıkaran zamansız ve eğlenceli bir düğün davetiyesi.",
    "descEN": "A playful interactive Save the Date where guests pull the lever to reveal your wedding date via a spinning slot machine.",
    "preview": "images/slot-hero-dark.png",
    "features": ["countdown", "music", "gallery", "rsvp"],
    "badge": "YENİ",
    "featured": true,
    "order": 2,
    "cardStyle": {
      "bg": "images/slot-hero-dark.png",
      "kolBg": "img/koleksiyonlar görsel/Timeless Lucky karanlık.png",
      "kolBgLight": "img/koleksiyonlar görsel/Timeless lucky aydınlık.png",
      "theme": "timeless",
      "invLabel": "SAVE THE DATE",
      "name1Field": "bride-name",
      "ampText": "&",
      "name2Field": "groom-name",
      "dateField": "event-date"
    },
    "segments": [
      {
        "id": null,
        "tabLabel": null,
        "labelTR": "Düğün",
        "labelEN": "Wedding",
        "scrollTarget": "hero",
        "tabKey": null,
        "timelineFormat": "slot-machine",
        "timelineItems": [
          { "time": "17:00", "title": "Konvoy",             "icon": "images/car.png" },
          { "time": "19:00", "title": "Nikâh & Karşılama",  "icon": "images/arch.png" },
          { "time": "20:00", "title": "İlk Dans & Kutlama", "icon": "images/couple.png" },
          { "time": "21:00", "title": "Pasta & Takı",       "icon": "images/cake.png" },
          { "time": "22:00", "title": "After Party",        "icon": "images/party.png" }
        ],
        "sectionGroups": [
          { "id": "couple",   "labelTR": "Çift Bilgileri", "labelEN": "Couple Details",  "scrollTarget": "hero" },
          { "id": "datetime", "labelTR": "Tarih & Saat",   "labelEN": "Date & Time",     "scrollTarget": "hero" },
          { "id": "venue",    "labelTR": "Mekan",          "labelEN": "Venue",           "scrollTarget": "venue" },
          { "id": "message",  "labelTR": "Davet Metni",    "labelEN": "Invitation Text", "scrollTarget": "message" },
          { "id": "family",   "labelTR": "Aile İsimleri",  "labelEN": "Family Names",    "scrollTarget": "family" }
        ],
        "fieldMap": [
          { "id": "bride-name",     "section": "couple",   "type": "text",     "labelTR": "Gelin Adı",    "labelEN": "Bride Name",      "placeholder": "Elif",                       "defaultValue": "ELİF" },
          { "id": "groom-name",     "section": "couple",   "type": "text",     "labelTR": "Damat Adı",    "labelEN": "Groom Name",      "placeholder": "Arda",                       "defaultValue": "ARDA" },
          { "id": "event-date",     "section": "datetime", "type": "text",     "labelTR": "Tarih",        "labelEN": "Date",            "placeholder": "14 EYLÜL 2026",              "defaultValue": "14 EYLÜL 2026" },
          { "id": "event-time",     "section": "datetime", "type": "time",     "labelTR": "Saat",         "labelEN": "Time",            "placeholder": "20:00",                      "defaultValue": "20:00" },
          { "id": "venue-name",     "section": "venue",    "type": "text",     "labelTR": "Mekan Adı",    "labelEN": "Venue Name",      "placeholder": "Çırağan Palace",             "defaultValue": "ÇIRAĞAN PALACE" },
          { "id": "venue-address",  "section": "venue",    "type": "text",     "labelTR": "Adres",        "labelEN": "Address",         "placeholder": "İstanbul",                   "defaultValue": "Yıldız, Çırağan Cd. No:32, Beşiktaş / İstanbul" },
          { "id": "map-link",       "section": "venue",    "type": "url",      "labelTR": "Harita URL",   "labelEN": "Map URL",         "placeholder": "https://maps.google.com/...", "defaultValue": "" },
          { "id": "invite-message", "section": "message",  "type": "textarea", "labelTR": "Davet Metni",  "labelEN": "Invitation Text", "placeholder": "Bu özel günümüzde...",       "defaultValue": "Bu özel günümüzde sizleri de aramızda görmekten mutluluk duyarız." },
          { "id": "bride-family",   "section": "family",   "type": "text",     "labelTR": "Gelin Ailesi", "labelEN": "Bride Family",    "placeholder": "DEMİR AİLESİ",               "defaultValue": "DEMİR AİLESİ" },
          { "id": "groom-family",   "section": "family",   "type": "text",     "labelTR": "Damat Ailesi", "labelEN": "Groom Family",    "placeholder": "AKSOY AİLESİ",               "defaultValue": "AKSOY AİLESİ" }
        ]
      }
    ],
    "folder": "Slot Machine"
  },
  {
    "id": "dugun-kina",
    "demo": "index.html",
    "nameTR": "Timeless Duo",
    "nameEN": "Timeless Duo",
    "catTR": "Düğün & Kına",
    "catEN": "Wedding & Henna Night",
    "descTR": "İki kutlama, tek hikâye; kına ve düğün detaylarını zarif bir deneyimde buluşturan koleksiyon.",
    "descEN": "Two celebrations, one story — wedding and henna details united in an elegant experience.",
    "preview": "images/wedding-slide-1.jfif",
    "features": [
      "countdown",
      "music",
      "gallery",
      "rsvp",
      "timeline",
      "upload"
    ],
    "badge": "POPÜLER",
    "featured": true,
    "order": 2,
    "cardStyle": {
      "bg": "images/wedding-slide-1.jfif",
      "kolBg": "img/koleksiyonlar görsel/Timeless duo karanlık.png",
      "kolBgLight": "img/koleksiyonlar görsel/Timeless duo aydınlık.png",
      "theme": "kina-split",
      "invLabel": "DÜĞÜN & KINA GECESİ",
      "name1Field": "bride-name",
      "ampText": "&",
      "name2Field": "groom-name",
      "dateField": "event-date-wedding",
      "date2Field": "event-date-henna"
    },
    "segments": [
      {
        "id": "wedding",
        "tabLabel": "DÜĞÜN",
        "labelTR": "Düğün",
        "labelEN": "Wedding",
        "scrollTarget": "wedding-cover",
        "tabKey": "wedding",
        "timelineFormat": "dugun-kina",
        "timelineItems": [
          {
            "time": "16:00",
            "title": "Konvoy",
            "icon": "images/car.png"
          },
          {
            "time": "19:00",
            "title": "Nikâh & Karşılama",
            "icon": "images/arch.png"
          },
          {
            "time": "20:00",
            "title": "İlk Dans & Kutlama",
            "icon": "images/couple.png"
          },
          {
            "time": "21:00",
            "title": "Pasta & Takı",
            "icon": "images/cake.png"
          },
          {
            "time": "22:00",
            "title": "After Party",
            "icon": "images/party.png"
          }
        ],
        "sectionGroups": [
          {
            "id": "couple",
            "labelTR": "Çift Bilgileri",
            "labelEN": "Couple Details",
            "scrollTarget": "wedding-cover"
          },
          {
            "id": "wedding",
            "labelTR": "Düğün Bilgileri",
            "labelEN": "Wedding Info",
            "scrollTarget": "wedding-cover"
          },
          {
            "id": "wedding-venue",
            "labelTR": "Düğün Mekanı",
            "labelEN": "Wedding Venue",
            "scrollTarget": "wedding-venue"
          }
        ],
        "fieldMap": [
          {
            "id": "bride-name",
            "section": "couple",
            "type": "text",
            "labelTR": "Gelin Adı",
            "labelEN": "Bride Name",
            "placeholder": "Senem",
            "defaultValue": "SENEM"
          },
          {
            "id": "groom-name",
            "section": "couple",
            "type": "text",
            "labelTR": "Damat Adı",
            "labelEN": "Groom Name",
            "placeholder": "Mehmet",
            "defaultValue": "MEHMET"
          },
          {
            "id": "event-date-wedding",
            "section": "wedding",
            "type": "text",
            "labelTR": "Düğün Tarihi & Saati",
            "labelEN": "Wedding Date & Time",
            "placeholder": "23 AĞUSTOS 2026 · 20.00",
            "defaultValue": "23 AĞUSTOS 2026 · 20.00"
          },
          {
            "id": "invite-message-wedding",
            "section": "wedding",
            "type": "textarea",
            "labelTR": "Düğün Davet Metni",
            "labelEN": "Wedding Text",
            "placeholder": "Bu mutlu günümüzde...",
            "defaultValue": "Bu mutlu günümüzde sizleri de aramızda görmekten mutluluk duyarız."
          },
          {
            "id": "venue-name-wedding",
            "section": "wedding-venue",
            "type": "text",
            "labelTR": "Düğün Mekanı",
            "labelEN": "Wedding Venue",
            "placeholder": "Gloria Meram",
            "defaultValue": "GLORIA MERAM"
          },
          {
            "id": "venue-address-wedding",
            "section": "wedding-venue",
            "type": "text",
            "labelTR": "Adres",
            "labelEN": "Address",
            "placeholder": "Konya",
            "defaultValue": "Lalebahçe, Özgüven Sk. No:1, 42140 Meram/Konya"
          },
          {
            "id": "map-link",
            "section": "wedding-venue",
            "type": "url",
            "labelTR": "Harita URL",
            "labelEN": "Map URL",
            "placeholder": "https://maps.google.com/...",
            "defaultValue": ""
          }
        ]
      },
      {
        "id": "henna",
        "tabLabel": "KINA",
        "labelTR": "Kına",
        "labelEN": "Henna Night",
        "scrollTarget": "henna-cover",
        "tabKey": "henna",
        "timelineFormat": "dugun-kina-henna",
        "timelineItems": [
          {
            "time": "20:00",
            "title": "Kına Girişi",
            "icon": "images/arch.png"
          },
          {
            "time": "21:00",
            "title": "Kına Yakılışı",
            "icon": "images/kina-yakimi.png"
          },
          {
            "time": "21:30",
            "title": "Testi Kırılışı",
            "icon": "images/testi-kirma.png"
          },
          {
            "time": "22:00",
            "title": "After Party",
            "icon": "images/party.png"
          }
        ],
        "sectionGroups": [
          {
            "id": "henna",
            "labelTR": "Kına Bilgileri",
            "labelEN": "Henna Info",
            "scrollTarget": "henna-cover"
          },
          {
            "id": "henna-venue",
            "labelTR": "Kına Mekanı",
            "labelEN": "Henna Venue",
            "scrollTarget": "henna-venue"
          }
        ],
        "fieldMap": [
          {
            "id": "henna-name",
            "section": "henna",
            "type": "text",
            "labelTR": "Gelin Kına Adı",
            "labelEN": "Bride Henna Name",
            "placeholder": "Senem'in",
            "defaultValue": "Senem'in"
          },
          {
            "id": "event-date-henna",
            "section": "henna",
            "type": "text",
            "labelTR": "Kına Tarihi & Saati",
            "labelEN": "Henna Date & Time",
            "placeholder": "21 AĞUSTOS 2026 · 20.00",
            "defaultValue": "21 AĞUSTOS 2026 · 20.00"
          },
          {
            "id": "invite-message-henna",
            "section": "henna",
            "type": "textarea",
            "labelTR": "Kına Davet Metni",
            "labelEN": "Henna Invitation Text",
            "placeholder": "Bu özel gecemizde...",
            "defaultValue": "Bu özel gecemizde siz değerli dostlarımızı aramızda görmekten mutluluk duyarız."
          },
          {
            "id": "venue-name-henna",
            "section": "henna-venue",
            "type": "text",
            "labelTR": "Kına Mekanı",
            "labelEN": "Henna Venue",
            "placeholder": "Prenses Düğün Salonu",
            "defaultValue": "PRENSES DÜĞÜN SALONU"
          },
          {
            "id": "venue-address-henna",
            "section": "henna-venue",
            "type": "text",
            "labelTR": "Adres",
            "labelEN": "Address",
            "placeholder": "Selçuklu / Konya",
            "defaultValue": "Selçuklu / Konya"
          },
          {
            "id": "map-link",
            "section": "henna-venue",
            "type": "url",
            "labelTR": "Harita URL",
            "labelEN": "Map URL",
            "placeholder": "https://maps.google.com/...",
            "defaultValue": ""
          }
        ]
      }
    ],
    "folder": "DÜĞÜN-KINA WEBSİTE"
  },
  {
    "id": "bride-groom-party",
    "demo": "index.html",
    "nameTR": "Bachelorette",
    "nameEN": "Bachelorette",
    "catTR": "Bekârlığa Veda",
    "catEN": "Bachelor Party",
    "descTR": "Bride ve Groom gecelerini ayrı ayrı deneyimleyebileceğiniz modern ve etkileşimli bir davetiye koleksiyonu.",
    "descEN": "A modern and interactive invitation collection where Bride and Groom nights are experienced separately.",
    "preview": "images/bride-hero-bg-clean.png",
    "features": [
      "countdown",
      "music",
      "timeline"
    ],
    "badge": null,
    "featured": true,
    "order": 3,
    "cardStyle": {
      "bg": "images/bride-hero-bg-clean.png",
      "kolBg": "img/koleksiyonlar görsel/Bachelorette karanlık.png",
      "kolBgLight": "img/koleksiyonlar görsel/Bachelorette aydınlık.png",
      "theme": "neon-party",
      "invLabel": "Bride to Be",
      "name1Field": "bride-name",
      "dateField": "event-date-bride"
    },
    "segments": [
      {
        "id": "bride",
        "tabLabel": "BRIDE",
        "labelTR": "Gelin",
        "labelEN": "Bride",
        "scrollTarget": "bride-hero",
        "tabKey": "bride",
        "timelineFormat": "party-bride",
        "timelineItems": [
          {
            "time": "17:00",
            "title": "Toplanma Saati",
            "icon": "images/bride-team-neon.png",
            "desc": "Kızlar hazır, enerji yüksek."
          },
          {
            "time": "18:00",
            "title": "Etkinlik Başlangıcı",
            "icon": "images/groom-mic-neon.png",
            "desc": "Oyunlar, sorular ve tatlı kaos."
          },
          {
            "time": "19:00",
            "title": "Tatlı & Sohbet",
            "icon": "images/bride-glasses-neon.png",
            "desc": "Bol kahkaha, bol anı."
          },
          {
            "time": "20:30",
            "title": "Party Time",
            "icon": "images/bride-mic-neon.png",
            "desc": "Mikrofon sende, gece bizim."
          }
        ],
        "sectionGroups": [
          {
            "id": "bride",
            "labelTR": "Gelin Tarafı",
            "labelEN": "Bride Side",
            "scrollTarget": "bride-hero"
          },
          {
            "id": "bride-venue",
            "labelTR": "Gelin Mekanı",
            "labelEN": "Bride Venue",
            "scrollTarget": "bride-hero"
          }
        ],
        "fieldMap": [
          {
            "id": "bride-name",
            "section": "bride",
            "type": "text",
            "labelTR": "Gelin Adı",
            "labelEN": "Bride Name",
            "placeholder": "Güzide",
            "defaultValue": "Güzide"
          },
          {
            "id": "event-date-bride",
            "section": "bride",
            "type": "text",
            "labelTR": "Gelin Gecesi Tarihi",
            "labelEN": "Bride Date",
            "placeholder": "21 HAZİRAN 2026",
            "defaultValue": "21 HAZİRAN 2026"
          },
          {
            "id": "event-time-bride",
            "section": "bride",
            "type": "text",
            "labelTR": "Saat",
            "labelEN": "Time",
            "placeholder": "20.30",
            "defaultValue": "20.30"
          },
          {
            "id": "venue-bride",
            "section": "bride-venue",
            "type": "text",
            "labelTR": "Mekan Adı",
            "labelEN": "Venue Name",
            "placeholder": "Garden Terrace",
            "defaultValue": "GARDEN TERRACE"
          },
          {
            "id": "venue-city-bride",
            "section": "bride-venue",
            "type": "text",
            "labelTR": "Şehir",
            "labelEN": "City",
            "placeholder": "Konya",
            "defaultValue": "Konya"
          },
          {
            "id": "map-link",
            "section": "bride-venue",
            "type": "url",
            "labelTR": "Harita URL",
            "labelEN": "Map URL",
            "placeholder": "https://maps.google.com/...",
            "defaultValue": ""
          }
        ]
      },
      {
        "id": "groom",
        "tabLabel": "GROOM",
        "labelTR": "Damat",
        "labelEN": "Groom",
        "scrollTarget": "groom-hero",
        "tabKey": "groom",
        "timelineFormat": "party-groom",
        "timelineItems": [
          {
            "time": "17:00",
            "title": "Toplanma Saati",
            "icon": "images/groom-team-neon.png",
            "desc": "Ekip tamam, gece başlıyor."
          },
          {
            "time": "18:00",
            "title": "Etkinlik Başlangıcı",
            "icon": "images/groom-dice-neon.png",
            "desc": "Oyunlar, iddialar ve kahkaha."
          },
          {
            "time": "19:00",
            "title": "Tatlı & Sohbet",
            "icon": "images/groom-glasses-neon.png",
            "desc": "Cool masa, sağlam muhabbet."
          },
          {
            "time": "20:30",
            "title": "Party Time",
            "icon": "images/bride-dice-neon.png",
            "desc": "Sahne damat ekibinin."
          }
        ],
        "sectionGroups": [
          {
            "id": "groom",
            "labelTR": "Damat Tarafı",
            "labelEN": "Groom Side",
            "scrollTarget": "groom-hero"
          },
          {
            "id": "groom-venue",
            "labelTR": "Damat Mekanı",
            "labelEN": "Groom Venue",
            "scrollTarget": "groom-hero"
          }
        ],
        "fieldMap": [
          {
            "id": "groom-name",
            "section": "groom",
            "type": "text",
            "labelTR": "Damat Adı",
            "labelEN": "Groom Name",
            "placeholder": "Abdullah",
            "defaultValue": "Abdullah"
          },
          {
            "id": "event-date-groom",
            "section": "groom",
            "type": "text",
            "labelTR": "Damat Gecesi Tarihi",
            "labelEN": "Groom Date",
            "placeholder": "21 HAZİRAN 2026",
            "defaultValue": "21 HAZİRAN 2026"
          },
          {
            "id": "event-time-groom",
            "section": "groom",
            "type": "text",
            "labelTR": "Saat",
            "labelEN": "Time",
            "placeholder": "20.30",
            "defaultValue": "20.30"
          },
          {
            "id": "venue-groom",
            "section": "groom-venue",
            "type": "text",
            "labelTR": "Mekan Adı",
            "labelEN": "Venue Name",
            "placeholder": "City Garden Rooftop",
            "defaultValue": "CITY GARDEN ROOFTOP"
          },
          {
            "id": "venue-city-groom",
            "section": "groom-venue",
            "type": "text",
            "labelTR": "Şehir",
            "labelEN": "City",
            "placeholder": "Konya",
            "defaultValue": "Konya"
          },
          {
            "id": "map-link",
            "section": "groom-venue",
            "type": "url",
            "labelTR": "Harita URL",
            "labelEN": "Map URL",
            "placeholder": "https://maps.google.com/...",
            "defaultValue": ""
          }
        ]
      }
    ],
    "folder": "bride-groom party"
  },
  {
    "id": "timeless-garden",
    "demo": "index.html",
    "nameTR": "Timeless Vow",
    "nameEN": "Timeless Vow",
    "catTR": "Nişan",
    "catEN": "Engagement",
    "descTR": "İki kalbin birbirine verdiği sözü zarif ve zamansız detaylarla kutlayan özel bir koleksiyon.",
    "descEN": "A special collection celebrating the vow between two hearts with elegant and timeless details.",
    "preview": "images/preview.svg",
    "features": [
      "countdown",
      "music",
      "gallery",
      "watermark"
    ],
    "badge": "YENİ",
    "featured": true,
    "order": 4,
    "cardStyle": {
      "bg": "images/preview.svg",
      "kolBg": "img/koleksiyonlar görsel/Timeless Vow karanlık.png",
      "kolBgLight": "img/koleksiyonlar görsel/Timeless Vow aydınlık.png",
      "theme": "cinematic",
      "invLabel": "NİŞAN DAVETİYESİ",
      "name1Field": "bride-name",
      "ampText": "&",
      "name2Field": "groom-name",
      "dateField": "event-date"
    },
    "segments": [
      {
        "id": null,
        "tabLabel": null,
        "labelTR": "Düğün",
        "labelEN": "Wedding",
        "scrollTarget": "hero",
        "tabKey": null,
        "timelineFormat": "timeless-garden",
        "timelineItems": [],
        "sectionGroups": [
          {
            "id": "couple",
            "labelTR": "Çift Bilgileri",
            "labelEN": "Couple Details",
            "scrollTarget": "hero"
          },
          {
            "id": "message",
            "labelTR": "Davet Metni",
            "labelEN": "Invitation Text",
            "scrollTarget": "hero"
          },
          {
            "id": "datetime",
            "labelTR": "Tarih & Saat",
            "labelEN": "Date & Time",
            "scrollTarget": "date"
          },
          {
            "id": "venue",
            "labelTR": "Mekan",
            "labelEN": "Venue",
            "scrollTarget": "venue"
          },
          {
            "id": "contact",
            "labelTR": "İletişim",
            "labelEN": "Contact",
            "scrollTarget": "contact"
          }
        ],
        "fieldMap": [
          {
            "id": "invitation-type",
            "section": "couple",
            "type": "text",
            "labelTR": "Davet Türü",
            "labelEN": "Invitation Type",
            "placeholder": "NİŞAN / DÜĞÜN / KINA…",
            "defaultValue": "NİŞAN DAVETİYESİ"
          },
          {
            "id": "bride-name",
            "section": "couple",
            "type": "text",
            "labelTR": "Gelin Adı",
            "labelEN": "Bride Name",
            "placeholder": "Büşra",
            "defaultValue": "BÜŞRA"
          },
          {
            "id": "groom-name",
            "section": "couple",
            "type": "text",
            "labelTR": "Damat Adı",
            "labelEN": "Groom Name",
            "placeholder": "Sinan",
            "defaultValue": "SİNAN"
          },
          {
            "id": "invite-message",
            "section": "message",
            "type": "textarea",
            "labelTR": "Davet Metni",
            "labelEN": "Invitation Text",
            "placeholder": "Davet mesajı…",
            "defaultValue": "Bu güzel anımıza tanıklık etmeniz için sizi aramızda görmekten mutluluk duyarız."
          },
          {
            "id": "event-date",
            "section": "datetime",
            "type": "text",
            "labelTR": "Tarih",
            "labelEN": "Date",
            "placeholder": "23 AĞUSTOS 2026",
            "defaultValue": "23 AĞUSTOS 2026"
          },
          {
            "id": "event-time",
            "section": "datetime",
            "type": "text",
            "labelTR": "Saat",
            "labelEN": "Time",
            "placeholder": "20:00",
            "defaultValue": "20:00"
          },
          {
            "id": "event-date-iso",
            "section": "datetime",
            "type": "text",
            "labelTR": "Geri Sayım (YYYY-AA-GG)",
            "labelEN": "Countdown (YYYY-MM-DD)",
            "placeholder": "2026-08-23",
            "defaultValue": "2026-08-23"
          },
          {
            "id": "venue-name",
            "section": "venue",
            "type": "text",
            "labelTR": "Mekan Adı",
            "labelEN": "Venue Name",
            "placeholder": "Gloria Meram",
            "defaultValue": "GLORIA MERAM"
          },
          {
            "id": "venue-subtitle",
            "section": "venue",
            "type": "text",
            "labelTR": "Mekan Türü",
            "labelEN": "Venue Type",
            "placeholder": "DÜĞÜN SALONU",
            "defaultValue": "DÜĞÜN SALONU"
          },
          {
            "id": "venue-address",
            "section": "venue",
            "type": "text",
            "labelTR": "Adres",
            "labelEN": "Address",
            "placeholder": "Adres…",
            "defaultValue": "Alaeviye Mah. Yeni Meram Cd. No:169\nMeram / KONYA"
          },
          {
            "id": "map-link",
            "section": "venue",
            "type": "url",
            "labelTR": "Harita URL",
            "labelEN": "Map URL",
            "placeholder": "https://maps.google.com/...",
            "defaultValue": ""
          },
          {
            "id": "whatsapp-number",
            "section": "contact",
            "type": "text",
            "labelTR": "WhatsApp Numarası",
            "labelEN": "WhatsApp Number",
            "placeholder": "905XXXXXXXXX",
            "defaultValue": "905372395824"
          },
          {
            "id": "instagram-handle",
            "section": "contact",
            "type": "text",
            "labelTR": "Instagram Kullanıcı Adı",
            "labelEN": "Instagram Handle",
            "placeholder": "davetiye_visora",
            "defaultValue": "davetiye_visora"
          }
        ]
      }
    ],
    "folder": "timeless-garden"
  },
  {
    "id": "film-strip",
    "demo": "index.html",
    "nameTR": "Timeless Cinematic",
    "nameEN": "Timeless Cinematic",
    "catTR": "Düğün",
    "catEN": "Wedding",
    "price": "standard",
    "badge": "YENİ",
    "descTR": "Film şeridinden ilham alan tasarımıyla en değerli anlarınızı etkileyici bir şekilde sergiler.",
    "descEN": "Inspired by film strips, it showcases your most precious moments in a cinematic and striking way.",
    "galleryLabel":   "Film Şeridi Fotoğrafları",
    "galleryLabelEN": "Film Strip Photos",
    "spiralGallery":  true,
    "cardStyle": {
      "accent": "#c8a96e",
      "textColor": "#1a1208",
      "bg": "images/thumb.jpg",
      "kolBg": "img/koleksiyonlar görsel/Timeless cinematic karanlık.png",
      "kolBgLight": "img/koleksiyonlar görsel/timeless cinematic aydınlık.png"
    },
    "segments": [
      {
        "id": "main",
        "labelTR": "Davetiye",
        "labelEN": "Invitation",
        "scrollTarget": "invitation",
        "fieldMap": [
          { "id": "bride-name",    "labelTR": "Gelin Adı",    "labelEN": "Bride's Name",   "type": "text",           "placeholder": "Ayşe",           "defaultValue": "Ayşe"           },
          { "id": "groom-name",    "labelTR": "Damat Adı",    "labelEN": "Groom's Name",   "type": "text",           "placeholder": "Mehmet",         "defaultValue": "Mehmet"         },
          { "id": "bride-family",  "labelTR": "Gelin Ailesi", "labelEN": "Bride's Family", "type": "text",           "placeholder": "Yılmaz Ailesi",  "defaultValue": "Yılmaz Ailesi"  },
          { "id": "groom-family",  "labelTR": "Damat Ailesi", "labelEN": "Groom's Family", "type": "text",           "placeholder": "Kara Ailesi",    "defaultValue": "Kara Ailesi"    },
          { "id": "event-date",    "labelTR": "Tarih",        "labelEN": "Date",           "type": "event-date",     "placeholder": "23 HAZİRAN 2026","defaultValue": "23 HAZİRAN 2026"},
          { "id": "event-date-iso","labelTR": "ISO Tarih",    "labelEN": "ISO Date",       "type": "event-date-iso", "placeholder": "2026-06-23",     "defaultValue": "2026-06-23"     },
          { "id": "event-time",    "labelTR": "Saat",         "labelEN": "Time",           "type": "event-time",     "placeholder": "19:00",          "defaultValue": "19:00"          },
          { "id": "venue",         "labelTR": "Mekan Adı",    "labelEN": "Venue",          "type": "text",           "placeholder": "Four Seasons",   "defaultValue": "Four Seasons Hotel" },
          { "id": "venue-city",    "labelTR": "Şehir",        "labelEN": "City",           "type": "text",           "placeholder": "İstanbul",       "defaultValue": "İstanbul"       },
          { "id": "address",       "labelTR": "Adres",        "labelEN": "Address",        "type": "text",           "placeholder": "Tam adres...",   "defaultValue": "Çırağan Cad. No:28, Beşiktaş / İstanbul" },
          { "id": "map-link",      "labelTR": "Harita Linki", "labelEN": "Map Link",       "type": "text",           "placeholder": "https://maps...", "defaultValue": ""              },
          { "id": "invite-message",     "labelTR": "Davet Mesajı",          "labelEN": "Invite Message",   "type": "invite-message", "placeholder": "Davet mesajı...",  "defaultValue": "Bu güzel anımıza tanıklık etmeniz için sizi aramızda görmekten mutluluk duyarız." },
          { "id": "whatsapp-number",    "labelTR": "WhatsApp Numarası",     "labelEN": "WhatsApp Number",  "type": "text",           "placeholder": "905XXXXXXXXX",     "defaultValue": "905372395824"    },
          { "id": "instagram-handle",   "labelTR": "Instagram Kullanıcı Adı","labelEN": "Instagram Handle", "type": "text",           "placeholder": "davetiye_visora",  "defaultValue": "davetiye_visora" }
        ]
      }
    ],
    "folder": "film-strip"
  },
  {
    "id": "cinematic-comparison-wedding",
    "demo": "index.html",
    "nameTR": "Timeless Flow",
    "nameEN": "Timeless Flow",
    "catTR": "Nişan",
    "catEN": "Engagement",
    "price": "standard",
    "badge": "YENİ",
    "featured": true,
    "descTR": "Aşk hikâyenizi zarif bir akış ve zamansız detaylarla misafirlerinize sunan özel koleksiyon.",
    "descEN": "A curated collection presenting your love story to guests with elegant flow and timeless details.",
    "cardStyle": {
      "accent": "#c8a96e",
      "textColor": "#faf8f3",
      "bg": "images/thumb.jpg",
      "kolBg": "img/koleksiyonlar görsel/Timeless flow karanlık.png",
      "kolBgLight": "img/koleksiyonlar görsel/Timeless flow aydınlık.png"
    },
    "segments": [
      {
        "id": "main",
        "labelTR": "Davetiye",
        "labelEN": "Invitation",
        "scrollTarget": "invitation",
        "timelineFormat": "program",
        "timelineItems": [
          { "time": "16:00", "title": "Konvoy",               "icon": "images/car.png",    "desc": "" },
          { "time": "19:00", "title": "Nikâh & Karşılama",    "icon": "images/arch.png",   "desc": "" },
          { "time": "20:00", "title": "İlk Dans & Kutlama",   "icon": "images/couple.png", "desc": "" },
          { "time": "21:00", "title": "Pasta & Takı",         "icon": "images/cake.png",   "desc": "" }
        ],
        "sectionGroups": [
          {
            "id": "names",
            "labelTR": "İsimler",
            "labelEN": "Names",
            "fieldMap": [
              { "id": "bride-name", "labelTR": "Gelin Adı",   "labelEN": "Bride's Name",  "type": "text", "placeholder": "Toprak"           },
              { "id": "groom-name", "labelTR": "Damat Adı",   "labelEN": "Groom's Name",  "type": "text", "placeholder": "Deniz"            },
              { "id": "subtitle",   "labelTR": "Alt Başlık",  "labelEN": "Subtitle",      "type": "text", "placeholder": "Düğün Davetiyesi" }
            ]
          },
          {
            "id": "families",
            "labelTR": "Aile İsimleri",
            "labelEN": "Family Names",
            "fieldMap": [
              { "id": "bride-family", "labelTR": "Gelin Ailesi",  "labelEN": "Bride's Family", "type": "text", "placeholder": "Yılmaz Ailesi" },
              { "id": "groom-family", "labelTR": "Damat Ailesi",  "labelEN": "Groom's Family", "type": "text", "placeholder": "Kara Ailesi"   }
            ]
          },
          {
            "id": "event",
            "labelTR": "Tarih & Saat",
            "labelEN": "Date & Time",
            "fieldMap": [
              { "id": "event-date",     "labelTR": "Tarih",    "labelEN": "Date",     "type": "event-date"     },
              { "id": "event-date-iso", "labelTR": "ISO Tarih","labelEN": "ISO Date", "type": "event-date-iso" },
              { "id": "event-time",     "labelTR": "Saat",     "labelEN": "Time",     "type": "event-time"     }
            ]
          },
          {
            "id": "venue",
            "labelTR": "Düğün Mekanı",
            "labelEN": "Venue",
            "fieldMap": [
              { "id": "venue",      "labelTR": "Mekan Adı",    "labelEN": "Venue Name", "type": "text", "placeholder": "Grand Hotel"    },
              { "id": "venue-city", "labelTR": "Şehir",        "labelEN": "City",       "type": "text", "placeholder": "İstanbul"       },
              { "id": "address",    "labelTR": "Adres",        "labelEN": "Address",    "type": "text", "placeholder": "Tam adres..."   },
              { "id": "map-link",   "labelTR": "Harita Linki", "labelEN": "Map Link",   "type": "text", "placeholder": "https://maps..." }
            ]
          },
          {
            "id": "message",
            "labelTR": "Davet Mesajı",
            "labelEN": "Invite Message",
            "fieldMap": [
              { "id": "invite-message", "labelTR": "Davet Mesajı", "labelEN": "Invite Message", "type": "invite-message" }
            ]
          }
        ]
      }
    ],
    "folder": "cinematic-comparison-wedding"
  }
];

/* ── Utility: computed paths (do not edit — regenerate instead) ── */
VISORA_TEMPLATES.forEach(function (t) {
  t._basePath  = 'davetiye websiteleri/' + t.folder + '/';
  t._demoUrl   = t._basePath + (t.demo || 'index.html');
  t._thumbUrl  = t._basePath + (t.preview || t.thumbnail || 'images/preview.jpg');
  t._createUrl = 'create.html?template=' + encodeURIComponent(t.id);

  if (t.cardStyle && t.cardStyle.bg) {
    t.cardStyle.bgUrl = t._basePath + t.cardStyle.bg;
  }

  /* Flatten first segment fields to top-level for backward compat */
  if (t.segments && t.segments.length > 0) {
    const first = t.segments[0];
    t.sectionGroups  = first.sectionGroups;
    t.fieldMap       = first.fieldMap;
    t.timelineItems  = first.timelineItems;
    t.timelineTarget = first.timelineFormat;
  }
});
